all:
	clang -fno-objc-arc -framework Foundation -framework CoreAudio -framework AVFoundation  -framework CoreMedia volume-capture-daemon.m -o ../../../../build/volume-capture-daemon
	chmod +x ../../../../build/volume-capture-daemon